### ISSUE TITLE
Can't delete the jar once I read the Manifest

### ISSUE THREAD

**Issue by eloiletagant** [desertnet/jarfile#4]
Hello!
Thanks for the job, I tested the package and it worked well... until I would delete the jar.
I use jarfile in an electron application and once I read infos from a jar, I need to delete it.
However, it seems the jar stays open, or used somewhere, because while the application is running I get an error when I try to delete it : 
`Error: EPERM: operation not permitted, lstat '<path_of_jar>'`

Do you have any idea about this ?

**Comment by limulus** [comment]
Hmm, unless there is some OS specific stuff going on, my understanding is that if you delete a file (`unlink()` it) while a process has it open, no error is thrown. The reference in the file system is removed, but processes that still have an open file descriptor can still access it. 

Based on the error message referencing `lstat()` I think you may be lacking a proper execute permission on an ancestor directory of the jar file. It’s weird that it only happens while your app is running though, but maybe something else is messing up the permissions of your directories?

If you can make reproducible test case I’m happy to investigate further!

**Comment by eloiletagant** [comment]
Thanks for answer :)
I'm on Windows 10 if you wonder..

I create a small electron app with only this read and delete jar : https://github.com/eloiletagant/jar-deletion
just clone, npm install and npm start to launch it, you'll see:
the 'success' message is displayed, but the jar is delete only when you close the app...
And I get same behaviour when the deletion is outside the callback!

Hope you'll find out what is going on :)

**Comment by limulus** [comment]
I ran it and wasn’t able to reproduce the issue. However, I’m on macOS, and I unfortunately don’t have a convenient way to test this on Windows currently.

Are you able to get the test case to reproduce the issue without the Electron dependency (just in a Node process)? Another thing to try might be to see if you can reproduce the issue just by using the `ls-archive` module, which is the dependency that `jarfile` uses to access the contents of the jar. If there is an issue, I think it’s likely to be an issue with `ls-archive`.

**Comment by eloiletagant** [comment]
You were right, it seems the error come from ls-archive dependency !
I should checked this before open an issue here, thanks for the help :)

**Comment by limulus** [comment]
No worries, issues with dependencies have a way of becoming issues with their dependents! 😄
