### ISSUE TITLE
Failed to parse valid manifest file due to incorrect regular expression 

### ISSUE THREAD

**Issue by shaon002** [desertnet/jarfile#5]
Steps to reproduce:
- parse a valid jdbc driver jar file. 
- the manifest.mf file contains entries as bellow:
        SHA-256-Digest: i68JQ1kocrRMFY73CPfLbGDIDnLKYDutWCyV2OVPs1M=

Seems that the problem is in the regular expression in Jar.js file:
      // Extract the name and value from entry line
        var pair = line.match(/^([a-z_-]+): (.*)$/i) 

The expression could be more generic to extract pair.

**Comment by limulus** [comment]
Thanks for this, @shaon002! I’ve just published v2.0.0 which should contain a fix. The reason for the major version bump was only because I dropped support for Node.js 0.12 (although it will likely continue to work for some time in 0.12).
